---
repo-name: peripherals-salesforce
categories:
- CRM
display-name: Salesforce
manufacture: Salesforce
product: "??"
description: Cloud based applications for sales, service, marketing, and more. A user-friendly
  UI allows for non-technical users to manage these services and tailor them for their
  own specific needs.
thumbnail: thumbnail.png
